# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('asWrapTry_rcpp_hello_world', PACKAGE = 'asWrapTry')
}

try_wrap_samdata <- function() {
    .Call('asWrapTry_try_wrap_samdata', PACKAGE = 'asWrapTry')
}

samId <- function(s) {
    .Call('asWrapTry_samId', PACKAGE = 'asWrapTry', s)
}

