# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('tryClass_rcpp_hello_world', PACKAGE = 'tryClass')
}

try_wrap_samdata <- function() {
    .Call('tryClass_try_wrap_samdata', PACKAGE = 'tryClass')
}

samId <- function(s) {
    .Call('tryClass_samId', PACKAGE = 'tryClass', s)
}

