// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP asWrapTry_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// try_wrap_samdata
SEXP try_wrap_samdata();
RcppExport SEXP asWrapTry_try_wrap_samdata() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(try_wrap_samdata());
    return __result;
END_RCPP
}
// samId
long samId(SEXP s);
RcppExport SEXP asWrapTry_samId(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type s(sSEXP);
    __result = Rcpp::wrap(samId(s));
    return __result;
END_RCPP
}
